### ISSUE TITLE
How many actors are being used in the A2C and PPO implementation

### ISSUE THREAD

**Issue by Ashutosh-Adhikari** [dongminlee94/deep_rl#1]
Hi @dongminlee94 , I am unable to find the notion of different actors in the A2C and PPO implementation from a brief skim. It would be great if you could point me there. Thanks!

**Comment by dongminlee94** [comment]
Hello~! @Ashutosh-Adhikari , Thank you for leaving good question~!! I think that you're finding synchronous actors or asynchronous actors in parallel system. Am I right?

**Comment by Ashutosh-Adhikari** [comment]
@dongminlee94 , if i understand your question correctly. Yes!

**Comment by dongminlee94** [comment]
@Ashutosh-Adhikari , I'll recommend some papers. Do you want to read them? And I think that you would be good to search for the implementation of related papers~!

- V. Minh et al., Asynchronous Methods for Deep Reinforcement Learning, 2016 (https://arxiv.org/abs/1602.01783)
- L. Espeholt et al., IMPALA: Scalable Distributed Deep-RL with Importance Weighted Actor-Learner Architectures, 2018 (https://arxiv.org/abs/1802.01561)
- A. Stooke et al., Accelerated Methods for Deep Reinforcement Learning, 2018 (https://arxiv.org/abs/1803.02811)
- XB. Peng et al., DeepMimic: Example-Guided Deep Reinforcement Learning of Physics-Based Character Skills, 2018 (https://arxiv.org/abs/1804.02717)

Actually, I haven't had much experience that I implemented synchronous actors or asynchronous actors in parallel system. I'm sorry it didn't help. I hope you find a good implementation from a brief skim in the A2C and PPO. Thank you~!
